# Source: mern/templates/secret.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-api
  labels:
    app.kubernetes.io/name: mern
    app.kubernetes.io/instance: mern-api
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  MONGOURI: <uri>
